---
language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  # NOTE: PyYAML currently fails on v3.7
  # - "3.7-dev" # 3.7 development branch
  # - "nightly"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y scrub
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
